#  Copyright 2026 Christopher Barber
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
"""
Semantic comparison of conda packages.

This module compares two conda packages - typically one generated by
whl2conda from a PyPI wheel and a reference package built from a recipe
(e.g. by conda-build or rattler-build for conda-forge) - and reports
their differences, classifying each as expected (benign differences
inherent to the different build processes), notable, or unexpected
errors.
"""

from __future__ import annotations

# standard
import email
import email.message
import email.policy
import enum
import json
import re
import tempfile
from dataclasses import dataclass, field
from functools import cached_property
from hashlib import sha256
from pathlib import Path
from typing import Any

# third party
import conda_package_handling.api as cphapi

# this project
from .converter import RequiresDistEntry
from .stdrename import load_std_renames

__all__ = [
    "CompareOptions",
    "ComparisonResult",
    "DiffCategory",
    "Difference",
    "Severity",
    "compare_conda_packages",
]

#: Dependencies that commonly appear only in recipe-built packages due
#: to compiler/interpreter run-exports or virtual package constraints.
STANDARD_RUN_EXPORTS: frozenset[str] = frozenset({
    "_python_abi3_support",
    "cpython",
    "libcxx",
    "libgcc",
    "libgcc-ng",
    "libstdcxx",
    "libstdcxx-ng",
    "libzlib",
    "python_abi",
    "ucrt",
    "vc",
    "vc14_runtime",
    "__glibc",
    "__osx",
    "__unix",
    "__win",
})

_BINARY_SUFFIXES = frozenset({".so", ".dylib", ".pyd", ".dll", ".exe", ".lib", ".a"})

_ABI3_BUILD_RE = re.compile(r"py\d+_abi3_\d+")

#: info/ entries that routinely exist in only one of the packages
_ONE_SIDED_INFO_RE = re.compile(
    r"info/(files|git|about\.json|link\.json|run_exports\.json|"
    r"hash_input\.json|recipe/.*|tests?/.*|licenses/.*)$"
)


class DiffCategory(enum.Enum):
    """Category of a difference between two conda packages."""

    # index.json / metadata
    PACKAGE_NAME = "package-name"
    PACKAGE_VERSION = "package-version"
    BUILD_STRING = "build-string"
    BUILD_NUMBER = "build-number"
    NOARCH_VS_PLATFORM = "noarch-vs-platform"
    LICENSE = "license"
    ABOUT_FIELD = "about-field"
    TIMESTAMP = "timestamp"
    # dependencies
    DEP_MISSING = "dep-missing"
    DEP_EXTRA = "dep-extra"
    DEP_RUN_EXPORT = "dep-run-export"
    DEP_VERSION = "dep-version"
    DEP_UNRENAMED = "dep-unrenamed"
    PYTHON_PIN = "python-pin"
    # files
    FILE_MISSING = "file-missing"
    FILE_EXTRA = "file-extra"
    FILE_CONTENT = "file-content"
    BINARY_CONTENT = "binary-content"
    PYCACHE = "pycache"
    ENTRY_POINT = "entry-point"
    # dist-info
    DIST_INFO_METADATA = "dist-info-metadata"
    DIST_INFO_OTHER = "dist-info-other"
    # info/ bookkeeping
    INFO_EXTRA_FILE = "info-extra-file"

    def __str__(self) -> str:
        return self.value


class Severity(enum.IntEnum):
    """Severity of a difference between two conda packages."""

    EXPECTED = 0
    """Benign difference inherent to the different build processes."""

    NOTICE = 1
    """Notable difference that is not necessarily a problem."""

    ERROR = 2
    """Unexpected difference that likely indicates a problem."""


@dataclass(frozen=True, slots=True)
class Difference:
    """A single difference between two conda packages."""

    category: DiffCategory
    """Category of the difference."""

    severity: Severity
    """Severity of the difference."""

    key: str
    """Locus of the difference, e.g. `index.json:depends` or a file path."""

    description: str
    """Human readable one line description."""

    left: Any = None
    """Relevant value from the first package, if any."""

    right: Any = None
    """Relevant value from the second (reference) package, if any."""

    def __str__(self) -> str:
        return f"{self.severity.name} {self.category} {self.key}: {self.description}"


@dataclass(slots=True)
class CompareOptions:
    """Options controlling conda package comparison."""

    strict: bool = False
    """Promote NOTICE differences to ERROR."""

    ignore: set[DiffCategory] = field(default_factory=set)
    """Categories demoted to EXPECTED severity."""

    extra_run_exports: set[str] = field(default_factory=set)
    """Additional dependency names treated as benign run-exports."""

    renames: dict[str, str] | None = None
    """pypi to conda package rename map.

    Defaults to the standard rename table from [load_std_renames][(m)..stdrename.].
    """


@dataclass(slots=True)
class ComparisonResult:
    """Result of comparing two conda packages."""

    package1: Path
    """First package (the package under test)."""

    package2: Path
    """Second package (the reference package)."""

    differences: list[Difference]
    """All differences found, including expected ones."""

    @property
    def errors(self) -> list[Difference]:
        """Differences with ERROR severity."""
        return [d for d in self.differences if d.severity >= Severity.ERROR]

    @property
    def ok(self) -> bool:
        """True if no ERROR severity differences were found."""
        return not self.errors

    def report(self, *, min_severity: Severity = Severity.NOTICE) -> str:
        """Generate a human readable report.

        Args:
            min_severity: only include differences of at least this severity.

        Returns:
            Multi-line report string.
        """
        lines = [f"Comparing {self.package1}", f"   against {self.package2}", ""]
        shown = [d for d in self.differences if d.severity >= min_severity]
        suppressed = len(self.differences) - len(shown)
        for d in sorted(shown, key=lambda d: (-d.severity, d.category.value, d.key)):
            lines.append(str(d))
            if d.left is not None:
                lines.append(f"    package1: {d.left}")
            if d.right is not None:
                lines.append(f"    package2: {d.right}")
        n_errors = len(self.errors)
        n_notices = sum(1 for d in self.differences if d.severity == Severity.NOTICE)
        lines.append("")
        summary = f"{n_errors} errors, {n_notices} notices"
        if suppressed:
            summary += f" ({suppressed} differences suppressed)"
        lines.append(summary)
        return "\n".join(lines)

    def to_json(self) -> dict[str, Any]:
        """JSON-compatible dictionary representation."""

        def _safe(val: Any) -> Any:
            if val is None or isinstance(val, (bool, int, float, str)):
                return val
            if isinstance(val, (list, tuple, set, frozenset)):
                return sorted(str(v) for v in val)
            return str(val)

        return {
            "package1": str(self.package1),
            "package2": str(self.package2),
            "ok": self.ok,
            "differences": [
                {
                    "category": d.category.value,
                    "severity": d.severity.name,
                    "key": d.key,
                    "description": d.description,
                    "left": _safe(d.left),
                    "right": _safe(d.right),
                }
                for d in self.differences
            ],
        }


def compare_conda_packages(
    package1: Path,
    package2: Path,
    *,
    options: CompareOptions | None = None,
) -> ComparisonResult:
    """Semantically compare two conda packages.

    The comparison is directional: `package1` is the package under
    test (e.g. generated by whl2conda) and `package2` is the reference
    package (e.g. from conda-forge). Differences that are inherent to
    the different build processes are reported with EXPECTED severity;
    differences that likely indicate a conversion problem are reported
    as errors.

    Args:
        package1: `.conda`/`.tar.bz2` file or extracted package directory
            for the package under test.
        package2: `.conda`/`.tar.bz2` file or extracted package directory
            for the reference package.
        options: comparison options.

    Returns:
        Comparison result with the list of differences found.
    """
    options = options or CompareOptions()
    with tempfile.TemporaryDirectory(prefix="whl2conda-compare-") as tmpdir:
        tmp_path = Path(tmpdir)
        pkg1 = _ExtractedPackage(_extract_if_needed(package1, tmp_path / "pkg1"))
        pkg2 = _ExtractedPackage(_extract_if_needed(package2, tmp_path / "pkg2"))
        comparer = _PackageComparer(pkg1, pkg2, options)
        differences = comparer.compare()
    return ComparisonResult(package1, package2, differences)


def _extract_if_needed(package: Path, dest_dir: Path) -> Path:
    if package.is_dir():
        return package
    dest_dir.mkdir(parents=True, exist_ok=True)
    cphapi.extract(str(package), dest_dir)
    return dest_dir


_SITE_PACKAGES_RE = re.compile(
    r"(?:[Ll]ib(?:/python\d+\.\d+)?/)?site-packages/(?P<rel>.+)$"
)
_SCRIPTS_RE = re.compile(r"(?:bin|Scripts|python-scripts)/(?P<rel>.+)$")

# ABI-specific part of an extension module file name, e.g.
# foo.cpython-313-darwin.so / foo.abi3.so / foo.cp313-win_amd64.pyd
_EXT_MODULE_TAG_RE = re.compile(
    r"\.(cpython-\d+t?[\w-]*|abi3|cp\d+t?[\w-]*|pypy\d*[\w-]*)(?P<suffix>\.(so|pyd))$"
)


class _ExtractedPackage:
    """Provides access to the contents of an extracted conda package."""

    root: Path

    def __init__(self, root: Path) -> None:
        self.root = root

    def _read_json(self, relpath: str) -> dict[str, Any]:
        path = self.root / relpath
        if not path.is_file():
            return {}
        return json.loads(path.read_text("utf8"))

    @cached_property
    def index(self) -> dict[str, Any]:
        return self._read_json("info/index.json")

    @cached_property
    def about(self) -> dict[str, Any]:
        return self._read_json("info/about.json")

    @cached_property
    def link(self) -> dict[str, Any]:
        return self._read_json("info/link.json")

    @cached_property
    def paths(self) -> dict[str, Any]:
        return self._read_json("info/paths.json")

    @cached_property
    def depends(self) -> dict[str, str]:
        """Runtime dependencies as a name to version-constraint map."""
        result: dict[str, str] = {}
        for dep in self.index.get("depends", ()):
            name, _, constraint = str(dep).partition(" ")
            result[name] = constraint.strip()
        return result

    @cached_property
    def all_files(self) -> list[str]:
        """All non-info files, relative to the package root."""
        return sorted(
            str(f.relative_to(self.root))
            for f in self.root.rglob("*")
            if f.is_file() and f.relative_to(self.root).parts[0] != "info"
        )

    @cached_property
    def payload(self) -> dict[str, str]:
        """Layout-normalized key to actual relative path map.

        Files under any site-packages directory get `site-packages/`
        keys, executable script dirs map to `scripts/`, and everything
        else keeps its own path.
        """
        result: dict[str, str] = {}
        for relpath in self.all_files:
            if m := _SITE_PACKAGES_RE.match(relpath):
                key = f"site-packages/{m.group('rel')}"
            elif m := _SCRIPTS_RE.match(relpath):
                key = f"scripts/{m.group('rel')}"
            else:
                key = relpath
            # strip the ABI-specific part of extension module names, so
            # that e.g. an abi3 build pairs up with a per-version build
            key = _EXT_MODULE_TAG_RE.sub(r"\g<suffix>", key)
            result[key] = relpath
        return result

    @cached_property
    def dist_info_key(self) -> str:
        """Normalized key prefix of the `*.dist-info` directory, if any."""
        for key in self.payload:
            parts = key.split("/")
            if len(parts) > 2 and parts[1].endswith(".dist-info"):
                return f"{parts[0]}/{parts[1]}"
        return ""

    @cached_property
    def entry_points(self) -> set[str]:
        """Entry point/script names from link.json and script dirs."""
        names: set[str] = set()
        for ep in self.link.get("noarch", {}).get("entry_points", ()):
            names.add(str(ep).partition("=")[0].strip())
        for key in self.payload:
            if key.startswith("scripts/"):
                name = key[len("scripts/") :]
                # normalize windows script launcher artifacts
                name = re.sub(r"(-script\.pyw?|\.exe|\.bat|\.cmd)$", "", name)
                names.add(name)
        return names

    def file_sha256(self, relpath: str) -> str:
        return sha256((self.root / relpath).read_bytes()).hexdigest()

    def metadata_msg(self, relpath: str) -> email.message.Message:
        content = (self.root / relpath).read_text("utf8")
        return email.message_from_string(content, policy=email.policy.default)


def _is_binary_file(key: str) -> bool:
    suffixes = Path(key).suffixes
    return bool(suffixes) and (
        suffixes[-1] in _BINARY_SUFFIXES
        or any(s in _BINARY_SUFFIXES for s in suffixes[-2:])
    )


def _is_pycache(key: str) -> bool:
    return "__pycache__/" in key or key.endswith(".pyc")


def _normalize_ws(text: str) -> str:
    return " ".join(str(text).split())


class _PackageComparer:
    """Compares the contents of two extracted conda packages."""

    def __init__(
        self,
        pkg1: _ExtractedPackage,
        pkg2: _ExtractedPackage,
        options: CompareOptions,
    ) -> None:
        self.pkg1 = pkg1
        self.pkg2 = pkg2
        self.options = options
        self.differences: list[Difference] = []
        self.run_exports = STANDARD_RUN_EXPORTS | options.extra_run_exports

    @cached_property
    def renames(self) -> dict[str, str]:
        renames = self.options.renames
        if renames is None:
            renames = load_std_renames()
        return {k: v for k, v in renames.items() if not k.startswith("$")}

    def compare(self) -> list[Difference]:
        """Run all checks and return the differences found."""
        self._check_index()
        self._check_depends()
        self._check_about()
        self._check_info_files()
        self._check_paths_consistency(self.pkg1, "package1")
        self._check_paths_consistency(self.pkg2, "package2")
        self._check_files()
        self._check_entry_points()
        self._check_dist_info()
        return self.differences

    def _add(
        self,
        category: DiffCategory,
        severity: Severity,
        key: str,
        description: str,
        *,
        left: Any = None,
        right: Any = None,
    ) -> None:
        if category in self.options.ignore:
            severity = Severity.EXPECTED
        elif self.options.strict and severity == Severity.NOTICE:
            severity = Severity.ERROR
        self.differences.append(
            Difference(category, severity, key, description, left, right)
        )

    #
    # index.json
    #

    def _check_index(self) -> None:
        index1 = self.pkg1.index
        index2 = self.pkg2.index

        if index1.get("name") != index2.get("name"):
            self._add(
                DiffCategory.PACKAGE_NAME,
                Severity.ERROR,
                "index.json:name",
                "package names differ",
                left=index1.get("name"),
                right=index2.get("name"),
            )
        if index1.get("version") != index2.get("version"):
            self._add(
                DiffCategory.PACKAGE_VERSION,
                Severity.ERROR,
                "index.json:version",
                "package versions differ",
                left=index1.get("version"),
                right=index2.get("version"),
            )

        subdir1, subdir2 = index1.get("subdir"), index2.get("subdir")
        noarch1, noarch2 = index1.get("noarch"), index2.get("noarch")
        if (subdir1, noarch1) != (subdir2, noarch2):
            # abi3/CEP-20 packages keep a platform subdir but set
            # noarch: python; either package may also be a pure noarch
            # equivalent of a platform-specific build.
            abi3 = any(
                _ABI3_BUILD_RE.fullmatch(str(ix.get("build", "")))
                for ix in (index1, index2)
            )
            severity = Severity.EXPECTED if abi3 else Severity.ERROR
            self._add(
                DiffCategory.NOARCH_VS_PLATFORM,
                severity,
                "index.json:subdir",
                "package subdir/noarch targets differ",
                left=f"subdir={subdir1} noarch={noarch1}",
                right=f"subdir={subdir2} noarch={noarch2}",
            )

        build1, build2 = index1.get("build"), index2.get("build")
        if build1 != build2:
            self._add(
                DiffCategory.BUILD_STRING,
                Severity.EXPECTED,
                "index.json:build",
                "build strings differ",
                left=build1,
                right=build2,
            )
        if index1.get("build_number", 0) != index2.get("build_number", 0):
            self._add(
                DiffCategory.BUILD_NUMBER,
                Severity.NOTICE,
                "index.json:build_number",
                "build numbers differ",
                left=index1.get("build_number"),
                right=index2.get("build_number"),
            )

        if index1.get("timestamp") != index2.get("timestamp"):
            self._add(
                DiffCategory.TIMESTAMP,
                Severity.EXPECTED,
                "index.json:timestamp",
                "timestamps differ",
            )

        license1 = str(index1.get("license") or "")
        license2 = str(index2.get("license") or "")
        if _normalize_ws(license1) != _normalize_ws(license2):
            self._add(
                DiffCategory.LICENSE,
                Severity.NOTICE,
                "index.json:license",
                "license fields differ (e.g. SPDX id vs full text)",
                left=license1[:60] or None,
                right=license2[:60] or None,
            )

    #
    # dependencies
    #

    def _check_depends(self) -> None:
        deps1 = self.pkg1.depends
        deps2 = self.pkg2.depends
        key = "index.json:depends"

        for name in sorted(deps1.keys() & deps2.keys()):
            if deps1[name] == deps2[name]:
                continue
            if name == "python":
                category = DiffCategory.PYTHON_PIN
                # an unconstrained python dependency on one side is
                # recipe/conversion boilerplate, not a real difference
                severity = (
                    Severity.EXPECTED
                    if not (deps1[name] and deps2[name])
                    else Severity.NOTICE
                )
            else:
                category = DiffCategory.DEP_VERSION
                severity = Severity.NOTICE
            self._add(
                category,
                severity,
                key,
                f"version constraints for dependency '{name}' differ",
                left=f"{name} {deps1[name]}".strip(),
                right=f"{name} {deps2[name]}".strip(),
            )

        only2 = deps2.keys() - deps1.keys()
        for name in sorted(only2):
            if name in self.run_exports:
                self._add(
                    DiffCategory.DEP_RUN_EXPORT,
                    Severity.EXPECTED,
                    key,
                    f"reference package has run-export style dependency '{name}'",
                    right=f"{name} {deps2[name]}".strip(),
                )
            else:
                self._add(
                    DiffCategory.DEP_MISSING,
                    Severity.ERROR,
                    key,
                    f"dependency '{name}' from reference package is missing",
                    right=f"{name} {deps2[name]}".strip(),
                )

        for name in sorted(deps1.keys() - deps2.keys()):
            conda_name = self.renames.get(name, name)
            if conda_name != name and conda_name in only2:
                self._add(
                    DiffCategory.DEP_UNRENAMED,
                    Severity.ERROR,
                    key,
                    f"dependency '{name}' was not renamed to conda name '{conda_name}'",
                    left=f"{name} {deps1[name]}".strip(),
                    right=f"{conda_name} {deps2[conda_name]}".strip(),
                )
            else:
                self._add(
                    DiffCategory.DEP_EXTRA,
                    Severity.NOTICE,
                    key,
                    f"dependency '{name}' not present in reference package",
                    left=f"{name} {deps1[name]}".strip(),
                )

    #
    # about.json
    #

    _ABOUT_FIELDS = ("summary", "home", "doc_url", "dev_url")

    def _check_about(self) -> None:
        about1 = self.pkg1.about
        about2 = self.pkg2.about
        for fld in self._ABOUT_FIELDS:
            val1, val2 = about1.get(fld), about2.get(fld)
            if val1 == val2:
                continue
            if val1 is None or val2 is None:
                # recipes routinely omit or add about fields
                severity = Severity.EXPECTED
            elif _normalize_ws(val1).lower() == _normalize_ws(val2).lower():
                continue
            else:
                severity = Severity.NOTICE
            self._add(
                DiffCategory.ABOUT_FIELD,
                severity,
                f"about.json:{fld}",
                f"about field '{fld}' differs",
                left=val1,
                right=val2,
            )

    #
    # info/ bookkeeping files
    #

    def _check_info_files(self) -> None:
        def info_files(pkg: _ExtractedPackage) -> set[str]:
            info_dir = pkg.root / "info"
            if not info_dir.is_dir():
                return set()
            return {
                str(f.relative_to(pkg.root)) for f in info_dir.rglob("*") if f.is_file()
            }

        files1 = info_files(self.pkg1)
        files2 = info_files(self.pkg2)
        for relpath in sorted(files1 ^ files2):
            side = "package1" if relpath in files1 else "package2"
            severity = (
                Severity.EXPECTED
                if _ONE_SIDED_INFO_RE.fullmatch(relpath)
                else Severity.NOTICE
            )
            self._add(
                DiffCategory.INFO_EXTRA_FILE,
                severity,
                relpath,
                f"info file only present in {side}",
            )

    #
    # paths.json internal consistency
    #

    def _check_paths_consistency(self, pkg: _ExtractedPackage, label: str) -> None:
        paths = pkg.paths.get("paths")
        if paths is None:
            return
        listed = {entry["_path"] for entry in paths}
        actual = set(pkg.all_files)
        for relpath in sorted(listed - actual):
            self._add(
                DiffCategory.FILE_MISSING,
                Severity.ERROR,
                f"paths.json:{relpath}",
                f"file listed in {label} paths.json does not exist",
            )
        for relpath in sorted(actual - listed):
            self._add(
                DiffCategory.FILE_EXTRA,
                Severity.ERROR,
                f"paths.json:{relpath}",
                f"file in {label} is not listed in its paths.json",
            )

    #
    # payload files
    #

    def _check_files(self) -> None:
        payload1 = self.pkg1.payload
        payload2 = self.pkg2.payload
        dist_info1 = self.pkg1.dist_info_key
        dist_info2 = self.pkg2.dist_info_key

        def is_dist_info(key: str, prefix: str) -> bool:
            return bool(prefix) and key.startswith(prefix + "/")

        for key in sorted(payload1.keys() - payload2.keys()):
            if _is_pycache(key):
                self._add(
                    DiffCategory.PYCACHE,
                    Severity.EXPECTED,
                    key,
                    "compiled python file only in package1",
                )
            elif is_dist_info(key, dist_info1):
                self._add(
                    DiffCategory.DIST_INFO_OTHER,
                    Severity.EXPECTED,
                    key,
                    "dist-info file only in package1",
                )
            else:
                self._add(
                    DiffCategory.FILE_EXTRA,
                    Severity.ERROR,
                    key,
                    "file only present in package1",
                )

        for key in sorted(payload2.keys() - payload1.keys()):
            if _is_pycache(key):
                self._add(
                    DiffCategory.PYCACHE,
                    Severity.EXPECTED,
                    key,
                    "compiled python file only in reference package",
                )
            elif is_dist_info(key, dist_info2):
                self._add(
                    DiffCategory.DIST_INFO_OTHER,
                    Severity.EXPECTED,
                    key,
                    "dist-info file only in reference package",
                )
            elif key.startswith("scripts/"):
                # entry point scripts are checked by name in _check_entry_points
                self._add(
                    DiffCategory.ENTRY_POINT,
                    Severity.EXPECTED,
                    key,
                    "script shipped as file in reference package",
                )
            elif key.startswith("etc/conda/test-files/"):
                self._add(
                    DiffCategory.INFO_EXTRA_FILE,
                    Severity.EXPECTED,
                    key,
                    "recipe test data only in reference package",
                )
            elif re.search(r"(^|/)(licenses?|share/doc)/", key, re.IGNORECASE):
                self._add(
                    DiffCategory.FILE_MISSING,
                    Severity.EXPECTED,
                    key,
                    "license/doc file only in reference package",
                )
            else:
                self._add(
                    DiffCategory.FILE_MISSING,
                    Severity.ERROR,
                    key,
                    "file from reference package is missing",
                )

        for key in sorted(payload1.keys() & payload2.keys()):
            if (
                _is_pycache(key)
                or is_dist_info(key, dist_info1)
                or key.startswith("scripts/")
            ):
                continue  # handled elsewhere / regenerated content
            sha1 = self.pkg1.file_sha256(payload1[key])
            sha2 = self.pkg2.file_sha256(payload2[key])
            if sha1 == sha2:
                continue
            if _is_binary_file(key):
                self._add(
                    DiffCategory.BINARY_CONTENT,
                    Severity.EXPECTED,
                    key,
                    "binary file contents differ (different build toolchains)",
                )
            else:
                self._add(
                    DiffCategory.FILE_CONTENT,
                    Severity.ERROR,
                    key,
                    "file contents differ",
                    left=sha1[:16],
                    right=sha2[:16],
                )

    #
    # entry points
    #

    def _check_entry_points(self) -> None:
        eps1 = self.pkg1.entry_points
        eps2 = self.pkg2.entry_points
        for name in sorted(eps1 ^ eps2):
            side = "package1" if name in eps1 else "reference package"
            self._add(
                DiffCategory.ENTRY_POINT,
                Severity.ERROR,
                f"entry-points:{name}",
                f"entry point '{name}' only present in {side}",
            )

    #
    # dist-info
    #

    def _check_dist_info(self) -> None:
        key1 = self.pkg1.dist_info_key
        key2 = self.pkg2.dist_info_key
        if not key1 or not key2:
            if key1 != key2:
                side = "package1" if key1 else "package2"
                self._add(
                    DiffCategory.DIST_INFO_OTHER,
                    Severity.NOTICE,
                    "dist-info",
                    f"only {side} contains a dist-info directory",
                    left=key1 or None,
                    right=key2 or None,
                )
            return

        md_relpath1 = self.pkg1.payload.get(f"{key1}/METADATA")
        md_relpath2 = self.pkg2.payload.get(f"{key2}/METADATA")
        if not md_relpath1 or not md_relpath2:
            return

        md1 = self.pkg1.metadata_msg(md_relpath1)
        md2 = self.pkg2.metadata_msg(md_relpath2)

        for fld in ("Name", "Version"):
            if str(md1.get(fld, "")) != str(md2.get(fld, "")):
                self._add(
                    DiffCategory.DIST_INFO_METADATA,
                    Severity.ERROR,
                    f"dist-info:METADATA:{fld}",
                    f"METADATA {fld} differs",
                    left=md1.get(fld),
                    right=md2.get(fld),
                )

        reqs1 = self._requirements(md1)
        reqs2 = self._requirements(md2)
        if reqs1 != reqs2:
            self._add(
                DiffCategory.DIST_INFO_METADATA,
                Severity.NOTICE,
                "dist-info:METADATA:Requires-Dist",
                "METADATA requirements differ",
                left=sorted(reqs1 - reqs2) or None,
                right=sorted(reqs2 - reqs1) or None,
            )

    @staticmethod
    def _requirements(md: email.message.Message) -> set[str]:
        """Unconditional Requires-Dist entries as `name version` strings.

        Requirements hidden by whl2conda behind the `original` extra are
        unhidden; requirements with any other marker (platform conditions,
        optional extras) are excluded on both sides.
        """
        result: set[str] = set()
        for raw in md.get_all("Requires-Dist") or ():
            try:
                entry = RequiresDistEntry.parse(str(raw))
            except SyntaxError:
                result.add(_normalize_ws(raw))
                continue
            if entry.extra_marker_name == "original":
                if not entry.generic:
                    continue  # conditionally hidden by whl2conda
            elif entry.marker:
                continue  # optional extra or platform-conditional dep
            result.add(_normalize_ws(f"{entry.name} {entry.version}"))
        return result
